### ISSUE TITLE
为什么要把一个 option 对象拆成多个组件？

### ISSUE THREAD

**Issue by zoffyzhang** [dawiwt/react-component-echarts#1]
是有某种方面的提升，还是只是写法不同？

**Comment by zhixuanziben** [comment]
我也有这样的疑问，本来option复制粘贴一下就行，现在还要再把每个选项改写成组件。

**Comment by dawiwt** [comment]
@zoffyzhang @zhixuanziben 
1. 写法不同，组件式相对来说更直观，相对于配置便于维护。
2. 开发思维不同，将 option 数据分散到各组件中，动态数据存放在 state 中，不用关心动态数据与静态数据的合并操作。
3. 关于将每个选项改写成组件的问题，请看[这里](https://dawiwt.com/react-component-echarts/tools.html)，可将 option 生成组件式写法。
