### ISSUE TITLE
辅助工具的域名到期了，有什么解决办法吗

### ISSUE THREAD

**Issue by heptaluan** [dawiwt/react-component-echarts#20]
如题

**Comment by dawiwt** [comment]
1、域名已续费，辅助工具可以正常使用了
2、辅助工具也可以通过本地访问：

```
git clone https://github.com/dawiwt/react-component-echarts.git
cd react-component-echarts
git checkout gh-pages
npx http-server .
```
浏览器访问 http://127.0.0.1:8080

**Comment by heptaluan** [comment]
> 1、市场已续费，辅助工具可以正常使用了
> 2、辅助工具也可以通过本地访问：
> 
> ```
> git clone https://github.com/dawiwt/react-component-echarts.git
> cd react-component-echarts
> git checkout gh-pages
> npx http-server .
> ```
> 
> 浏览器访问http://127.0.0.1:8080



> 1、市场已续费，辅助工具可以正常使用了
> 2、辅助工具也可以通过本地访问：
> 
> ```
> git clone https://github.com/dawiwt/react-component-echarts.git
> cd react-component-echarts
> git checkout gh-pages
> npx http-server .
> ```
> 
> 浏览器访问http://127.0.0.1:8080

太感谢了！

**Comment by dawiwt** [comment]
[辅助工具](https://dawiwt.com/react-component-echarts/tools.html)
