### ISSUE TITLE
错误 Uncaught TypeError: Cannot read property 'resize' of null 

### ISSUE THREAD

**Issue by DAOLIDEWONIU** [dawiwt/react-component-echarts#3]
遇到这个问题，不知道怎么解决。Uncaught TypeError: Cannot read property 'resize' of null
    at ZRender.resize (:1111/vendors.async.js:127503)

**Comment by dawiwt** [comment]
能不能贴出你的代码，复现一下？

**Comment by DAOLIDEWONIU** [comment]
大概差不多，有时我切换页面 就会出现[代码](https://codesandbox.io/s/laughing-pare-9w7br?fontsize=14)

**Comment by DAOLIDEWONIU** [comment]
不知道为啥，找了好久 :(

**Comment by dawiwt** [comment]
由于你给出的[代码](https://codesandbox.io/s/laughing-pare-9w7br?fontsize=14)没有导入`Echarts`，所以不能运行；
我 [`fork`](https://codesandbox.io/embed/recharts-issues3-p90hg) 了一份，引入`Echarts`后正常运行；
可否将你遇到的详细错误日志（点开错误日志前的三角▶）截图发上来？或者复现一下问题？以便我定位问题，多谢！

**Comment by dawiwt** [comment]
@DAOLIDEWONIU 
你好，猜测你在切换页面时，触发了`DOM Resize Listen`以及图表的`Resize`，而由于切换页面时图表已销毁，所以导致了这个问题，我在`v0.1.6`中解决了这个问题，请更新。

**Comment by DAOLIDEWONIU** [comment]
嗯嗯，，谢谢！

**Comment by dawiwt** [comment]
Issue我先关了，有问题请重新开启。
